// ForgeFit V3 — coaching, records, échauffement, progression et sauvegardes
(function(){
  const BACKUP_KEY="forgefit_v3_backups";
  const css=document.createElement("style");
  css.textContent=`.ff-ex-head{justify-content:flex-start!important}.ff-thumb{flex:0 0 auto;width:auto;min-width:72px;height:36px;padding:0 9px;border-radius:999px;border:1px solid rgba(214,164,91,.35);background:#101012;color:var(--accent2);display:grid;place-items:center}.ff-thumb span{font-size:9px;font-weight:850;letter-spacing:.05em}.ff-ex-head>div{min-width:0;flex:1}.ff-insights{margin:9px 0;display:grid;gap:7px}.ff-insight{padding:9px 11px;border-radius:12px;background:#101012;border:1px solid var(--line);font-size:12px;line-height:1.4}.ff-target{color:var(--accent2)}.ff-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:9px}.ff-actions button{padding:10px}.ff-modal{position:fixed;inset:0;z-index:70;background:rgba(0,0,0,.78);display:flex;align-items:flex-end;justify-content:center;padding:16px 16px calc(16px + var(--safe-bottom));backdrop-filter:blur(8px)}.ff-modal-card{width:min(680px,100%);max-height:88vh;overflow:auto;background:#171719;border:1px solid var(--line);border-radius:28px;padding:20px}.ff-modal-visual{height:210px;border-radius:20px;background:#101012;border:1px solid var(--line);display:grid;place-items:center;margin:12px 0 16px;color:var(--accent2)}.ff-modal-visual svg{width:min(300px,85%);height:185px}.ff-muscles{display:flex;flex-wrap:wrap;gap:7px;margin:10px 0 16px}.ff-cue{padding:10px 0;border-bottom:1px solid var(--line);font-size:14px}.ff-dash{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.ff-dash .stat{min-height:82px}.ff-records{display:flex;flex-wrap:wrap;gap:6px}.ff-record{font-size:11px;color:var(--ok);border:1px solid rgba(126,201,149,.3);border-radius:999px;padding:7px 9px}.ff-prog{display:flex;justify-content:space-between;gap:10px;padding:10px 0;border-bottom:1px solid var(--line);font-size:13px}.ff-warm{display:flex;justify-content:space-between;padding:10px;margin-top:7px;background:#101012;border:1px solid var(--line);border-radius:12px}.ff-program-main{display:flex;align-items:center;gap:10px;min-width:0;flex:1}.ff-program-main .ff-thumb{width:auto;height:34px;flex-basis:auto}@media(max-width:420px){.ff-actions{grid-template-columns:1fr}}`;
  document.head.appendChild(css);
  const norm=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
  const done=e=>(e?.sets||[]).filter(s=>s.done);
  const vol=e=>done(e).reduce((a,s)=>a+(+s.weight||0)*(+s.reps||0),0);
  const fmt=v=>{const n=+v||0;return Number.isInteger(n)?String(n):n.toFixed(1).replace(".",",");};
  const sessions=()=>[...state.sessions].sort((a,b)=>new Date(a.endedAt)-new Date(b.endedAt));
  const hist=name=>sessions().map(s=>({s,e:(s.exercises||[]).find(x=>norm(x.name)===norm(name))})).filter(x=>x.e&&done(x.e).length);
  const minutes=s=>{if(!s||s.source==="mybodynote"||!s.endedAt)return null;const d=(new Date(s.endedAt)-new Date(s.startedAt))/60000;return d>0?Math.max(1,Math.round(d)):null;};
  function best(name){let weight=0,reps=0,e1=0,volume=0;hist(name).forEach(({e})=>{done(e).forEach(s=>{weight=Math.max(weight,+s.weight||0);reps=Math.max(reps,+s.reps||0);e1=Math.max(e1,estimated1RM(+s.weight||0,+s.reps||0));});volume=Math.max(volume,vol(e));});return{weight,reps,e1,volume};}
  function target(ex){
    if(state.reprise?.enabled)return{text:"Charge facile · RPE 6–7 · garde 3–4 reps en réserve",weight:0};
    const h=hist(ex.name),last=h.at(-1);if(!last)return{text:`Première référence : ${ex.targetReps} reps propres à RPE 7–8`,weight:+ex.suggestedWeight||0};
    const ds=done(last.e),w=Math.max(...ds.map(s=>+s.weight||0)),same=ds.filter(s=>(+s.weight||0)===w),r=same.reduce((a,s)=>a+(+s.reps||0),0)/same.length,rpes=same.map(s=>+s.rpe).filter(Boolean),rp=rpes.length?rpes.reduce((a,b)=>a+b,0)/rpes.length:8,step=ex.category==="lower"?(+state.settings.lowerIncrement||5):(+state.settings.upperIncrement||2.5);
    if(r>=+ex.targetReps&&rp<=8){const nw=roundTo(w+step,step);return{text:`Essaie ${fmt(nw)} kg × ${ex.targetReps}`,weight:nw};}
    if(rp>=9.5||r<+ex.targetReps-2){const nw=Math.max(step,roundTo(w-step,step));return{text:`Allège à ${fmt(nw)} kg et garde une exécution propre`,weight:nw};}
    return{text:`Garde ${fmt(w)} kg et gagne 1 rep sur au moins une série`,weight:w};
  }
  function nextAdvice(ex){const ds=done(ex);if(!ds.length)return target(ex).text;const s=ds.at(-1),w=+s.weight||0,r=+s.reps||0,rpe=+s.rpe||0,t=+ex.targetReps||0;if(rpe>=9.5||r<t-2)return`Baisse légèrement ou reste à ${fmt(w)} kg avec plus de marge.`;if(rpe&&rpe<=7&&r>=t)return`Garde ${fmt(w)} kg et vise ${t}-${t+1} reps.`;return`Garde ${fmt(w)} kg et vise ${t} reps propres.`;}
  function warmup(ex){const n=norm(ex.name);if(["elevation","curl","triceps","ecarte","mollet","crunch","releve","oiseau"].some(k=>n.includes(k)))return[];let w=target(ex).weight;if(!w){const h=hist(ex.name).at(-1);w=h?Math.max(...done(h.e).map(s=>+s.weight||0)):0;}if(w<12)return[];const st=ex.category==="lower"?5:2.5,rr=p=>Math.max(st,roundTo(w*p,st));return[{w:rr(.4),r:10},{w:rr(.65),r:5},{w:rr(.8),r:3}].filter((x,i,a)=>!i||x.w>a[i-1].w);}
  function showWarmup(ex){const a=warmup(ex);if(!a.length){alert("Sur cet exercice, quelques répétitions légères et contrôlées suffisent généralement.");return;}document.querySelector(".ff-modal")?.remove();const m=document.createElement("div");m.className="ff-modal";m.innerHTML=`<div class="ff-modal-card"><div class="row"><div><div class="eyebrow">ÉCHAUFFEMENT</div><h2>${esc(ex.name)}</h2></div><button class="ghost" data-x>Fermer</button></div><p class="muted small">Ces séries ne comptent pas dans les séries de travail.</p>${a.map((s,i)=>`<div class="ff-warm"><span>Série ${i+1}</span><b>${fmt(s.w)} kg × ${s.r}</b></div>`).join("")}</div>`;document.body.appendChild(m);m.querySelector("[data-x]").onclick=()=>m.remove();}
  function currentPR(ex){const b=best(ex.name),ds=done(ex);if(!ds.length)return[];const w=Math.max(...ds.map(s=>+s.weight||0)),e1=Math.max(...ds.map(s=>estimated1RM(+s.weight||0,+s.reps||0))),v=vol(ex),o=[];if(w>b.weight&&w)o.push(`Charge ${fmt(w)} kg`);if(e1>b.e1+.05&&e1)o.push(`1RM ${e1.toFixed(1)} kg`);if(v>b.volume&&v)o.push(`Volume ${Math.round(v).toLocaleString("fr-FR")} kg`);return o.slice(0,2);}
  function estimate(w){const same=state.sessions.filter(s=>s.workoutName===w?.name).map(minutes).filter(Boolean).slice(-3);if(same.length)return Math.round(same.reduce((a,b)=>a+b,0)/same.length);if(!w)return null;const sets=w.exercises.reduce((a,e)=>a+(+e.targetSets||0),0),rests=w.exercises.reduce((a,e)=>a+Math.max(0,(+e.targetSets||1)-1)*(+e.rest||90),0)/60;return Math.round(sets*.75+rests+w.exercises.length*1.5);}
  function highlights(){const last=sessions().at(-1);if(!last)return[];const o=[];last.exercises.forEach(e=>{const old=hist(e.name).filter(x=>x.s.id!==last.id).at(-1);if(!old)return;const a=Math.max(...done(e).map(s=>estimated1RM(+s.weight||0,+s.reps||0))),b=Math.max(...done(old.e).map(s=>estimated1RM(+s.weight||0,+s.reps||0)));if(a>b*1.01)o.push({name:e.name,text:`1RM estimé +${(a-b).toFixed(1)} kg`});else if(vol(old.e)>0&&vol(e)>vol(old.e)*1.04)o.push({name:e.name,text:`volume +${Math.round((vol(e)/vol(old.e)-1)*100)} %`});});return o.slice(0,3);}
  function backup(reason){try{const a=JSON.parse(localStorage.getItem(BACKUP_KEY)||"[]");a.push({at:new Date().toISOString(),reason,state:structuredClone(state)});while(a.length>5)a.shift();localStorage.setItem(BACKUP_KEY,JSON.stringify(a));}catch(e){}}
  function latestBackup(){try{return JSON.parse(localStorage.getItem(BACKUP_KEY)||"[]").at(-1);}catch(e){return null;}}
  function shareBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),file=new File([blob],`forgefit-backup-${new Date().toISOString().slice(0,10)}.json`,{type:"application/json"});if(navigator.share&&navigator.canShare?.({files:[file]}))navigator.share({title:"Sauvegarde ForgeFit",files:[file]}).catch(()=>{});else{const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=file.name;a.click();}}
  view.addEventListener("click",e=>{const b=e.target.closest?.('[data-action="done"]');if(!b||!state.activeSession)return;const c=b.closest(".exercise-card"),r=b.closest(".set-row"),ex=state.activeSession.exercises[+c.dataset.ei],s=ex?.sets?.[+r.dataset.si];if(ex&&s&&!s.done){ex._firstSetAt=ex._firstSetAt||new Date().toISOString();ex._lastSetAt=new Date().toISOString();}},true);

  const rp=renderProgram;renderProgram=function(){rp();const rows=[...view.querySelectorAll("section.card .list-item")];let i=0;state.program.forEach(w=>w.exercises.forEach(ex=>{const row=rows[i++],left=row?.firstElementChild;if(!left)return;const wrap=document.createElement("div");wrap.className="ff-program-main";const btn=document.createElement("button");btn.className="ff-thumb";btn.innerHTML="<span>TECHNIQUE</span>";btn.onclick=()=>FFGuide.open(ex.name);const info=document.createElement("div");info.append(...left.childNodes);wrap.append(btn,info);left.replaceWith(wrap);}));};
  const ra=renderActiveSession;renderActiveSession=function(){ra();const s=state.activeSession;if(!s)return;view.querySelectorAll(".exercise-card").forEach(card=>{const ex=s.exercises[+card.dataset.ei],row=card.querySelector(":scope > .row");if(!ex||!row)return;row.classList.add("ff-ex-head");if(!row.querySelector(".ff-thumb")){const b=document.createElement("button");b.className="ff-thumb";b.innerHTML="<span>TECHNIQUE</span>";b.onclick=()=>FFGuide.open(ex.name);row.prepend(b);}const meta=card.querySelector(".exercise-meta");if(meta&&!card.querySelector(".ff-insights")){const h=hist(ex.name).at(-1),last=h?done(h.e).slice(0,4).map(s=>`${s.weight||0} kg×${s.reps}`).join(" · "):"Aucune référence",prs=currentPR(ex),d=document.createElement("div");d.className="ff-insights";d.innerHTML=`<div class="ff-insight">Dernière fois : ${esc(last)}</div><div class="ff-insight ff-target"><b>Coach :</b> ${esc(nextAdvice(ex))}</div>${prs.length?`<div class="ff-records">${prs.map(x=>`<span class="ff-record">🏆 ${esc(x)}</span>`).join("")}</div>`:""}`;meta.parentElement.appendChild(d);}if(!card.querySelector(".ff-actions")){const a=document.createElement("div");a.className="ff-actions";a.innerHTML='<button class="ghost" data-move>Voir le mouvement</button><button class="ghost" data-warm>Échauffement</button><button class="secondary" data-add>+ Ajouter une série</button><button class="secondary" data-prog>Ma progression</button>';a.querySelector("[data-move]").onclick=()=>FFGuide.open(ex.name);a.querySelector("[data-warm]").onclick=()=>showWarmup(ex);a.querySelector("[data-add]").onclick=()=>{const l=ex.sets.at(-1);ex.sets.push({id:crypto.randomUUID(),index:ex.sets.length+1,weight:l?.weight||ex.suggestedWeight||"",reps:ex.targetReps,rpe:"",done:false});ex.targetSets=ex.sets.length;saveState();renderActiveSession();};a.querySelector("[data-prog]").onclick=()=>{histFilter="exercise";route="history";document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.route===route));render();setTimeout(()=>{const sel=document.querySelector("#exercise-filter");if(sel&&[...sel.options].some(o=>o.value===ex.name)){sel.value=ex.name;renderExerciseStats(ex.name);}},0);};card.appendChild(a);}});};
  const rt=renderToday;renderToday=function(){rt();if(state.activeSession)return;const w=state.program[nextWorkoutIndex()],hero=view.querySelector(".hero"),p=hero?.querySelector("p.muted");if(p&&w)p.innerHTML=`${w.exercises.length} exercices · <b style="color:var(--text)">≈ ${estimate(w)} min</b> · progression guidée`;const last=sessions().at(-1),d=document.createElement("section");d.className="card";d.innerHTML=`<div class="eyebrow">TABLEAU DE BORD</div><div class="ff-dash"><div class="stat"><b>${last?(minutes(last)||"—"):"—"}</b><span>min dernière séance</span></div><div class="stat"><b>${last?completedSets(last):"—"}</b><span>séries réalisées</span></div><div class="stat"><b>${state.reprise?.enabled?`${state.sessions.filter(s=>String(s.workoutName||"").startsWith("Reprise ")).length}/6`:"PPL"}</b><span>${state.reprise?.enabled?"reprise":"programme"}</span></div><div class="stat"><b>${w?estimate(w):"—"}</b><span>min prévues</span></div></div></section>`;hero?.insertAdjacentElement("afterend",d);const h=highlights();if(h.length){const q=document.createElement("section");q.className="card";q.innerHTML=`<div class="eyebrow">DERNIERS PROGRÈS</div>${h.map(x=>`<div class="ff-prog"><span>${esc(x.name)}</span><b class="badge-ok">${esc(x.text)}</b></div>`).join("")}`;d.insertAdjacentElement("afterend",q);}};
  const re=renderExerciseStats;renderExerciseStats=function(name){re(name);const box=document.querySelector("#exercise-stats");if(!box)return;const b=best(name),last=hist(name).at(-1),x=document.createElement("div");x.innerHTML=`<div class="ff-dash"><div class="stat"><b>${b.weight?fmt(b.weight):"—"}</b><span>record charge kg</span></div><div class="stat"><b>${b.reps||"—"}</b><span>record reps</span></div><div class="stat"><b>${b.e1?b.e1.toFixed(1):"—"}</b><span>meilleur 1RM</span></div><div class="stat"><b>${b.volume?Math.round(b.volume).toLocaleString("fr-FR"):"—"}</b><span>meilleur volume</span></div></div>${last?`<div class="ff-insight" style="margin-top:10px"><b>Dernière fois :</b> ${done(last.e).map(s=>`${s.weight||0}×${s.reps}`).join(" · ")}</div>`:""}`;box.prepend(x);};
  const rh=renderHistory;renderHistory=function(){rh();if(histFilter==="history"){const ss=[...state.sessions].sort((a,b)=>new Date(b.endedAt)-new Date(a.endedAt)),cards=[...document.querySelectorAll("#history-content > section.card")];cards.forEach((c,i)=>{const s=ss[i],d=c.querySelector("details");if(!s||!d)return;const a=s.exercises.filter(e=>e._firstSetAt&&e._lastSetAt);if(a.length){const x=document.createElement("div");x.className="small muted";x.style.marginTop="10px";x.textContent=a.map(e=>`${e.name} ~${Math.max(1,Math.round((new Date(e._lastSetAt)-new Date(e._firstSetAt))/60000))} min`).join(" · ");d.appendChild(x);}});}};
  const rs=renderSettings;renderSettings=function(){rs();const b=latestBackup(),s=document.createElement("section");s.className="card";s.innerHTML=`<div class="eyebrow">SAUVEGARDES</div><h3 style="margin-top:6px">Protection des données</h3><p class="muted small">Jusqu’à 5 sauvegardes locales sont gardées automatiquement. Pour changer d’iPhone, enregistre aussi le fichier dans Fichiers/iCloud.</p><div class="ff-insight">${b?`✓ Dernière sauvegarde : ${new Date(b.at).toLocaleString("fr-FR")}`:"Aucune sauvegarde"}</div><button class="secondary full" id="ff-backup" style="margin-top:10px">Partager / enregistrer une sauvegarde</button><div class="notice" style="margin-top:10px"><b>Synchro multi-appareils :</b> elle nécessitera un compte et un backend sécurisé ; aucune clé privée n’est stockée dans l’app.</div>`;view.appendChild(s);s.querySelector("#ff-backup").onclick=()=>{backup("manuel");shareBackup();renderSettings();};};
  const cm=coachMessage;coachMessage=function(){if(state.reprise?.enabled){const n=state.sessions.filter(s=>String(s.workoutName||"").startsWith("Reprise ")).length;return`Reprise ${Math.min(n+1,6)}/6 : RPE 6–7, amplitude propre et 3–4 répétitions en réserve.`;}const h=highlights();if(h.length)return`Tu progresses sur ${h[0].name}. Valide toutes tes séries proprement avant d’ajouter de la charge.`;return cm();};
  const fs=finishSession;finishSession=function(){const prs=state.activeSession?state.activeSession.exercises.flatMap(e=>currentPR(e).map(x=>`${e.name} — ${x}`)).slice(0,4):[];fs();backup("fin-seance");if(prs.length)setTimeout(()=>alert(`Nouveau record ✓\n\n${prs.join("\n")}`),80);};
  if(!latestBackup())backup("installation-v3");
  render();
})();
