// ForgeFit — module repas & courses. Les données sensibles restent hors du dépôt public.
(function(){
  const PERSON_KEY="forgefit_meals_person";
  const VIEW_KEY="forgefit_meals_view";
  const DAYS=[
    {name:"Lundi",lunch:["Poulet, riz basmati & ratatouille","180 g poulet · 90 g riz sec · 250 g ratatouille","120 g poulet · 60 g riz sec · 250 g ratatouille"],dinner:["Saumon, pommes de terre & haricots verts","180 g saumon · 300 g pommes de terre · 250 g haricots verts","130 g saumon · 220 g pommes de terre · 250 g haricots verts"],snack:["Skyr, fruits rouges & amandes","250 g skyr · 150 g fruits rouges · 20 g amandes","150 g skyr · 100 g fruits rouges · 15 g amandes"],shop:["300 g poulet","310 g saumon","150 g riz basmati sec","520 g pommes de terre","500 g ratatouille","500 g haricots verts","400 g skyr","250 g fruits rouges","35 g amandes","2 yaourts nature","1 citron"]},
    {name:"Mardi",lunch:["Dinde, pâtes complètes, épinards & tomate","180 g dinde · 90 g pâtes sèches · 200 g épinards","120 g dinde · 60 g pâtes sèches · 200 g épinards"],dinner:["Chili maison bœuf & haricots rouges","160 g bœuf 5% · 150 g haricots · 80 g riz sec","100 g bœuf 5% · 120 g haricots · 50 g riz sec"],snack:["Banane & fromage blanc","1 banane · 250 g fromage blanc","1 fruit · 150 g fromage blanc"],shop:["300 g dinde","260 g bœuf haché 5%","150 g pâtes complètes sèches","130 g riz sec","270 g haricots rouges cuits","400 g épinards","1 bocal sauce tomate","2 poivrons","2 oignons","400 g fromage blanc","2 fruits"]},
    {name:"Mercredi",lunch:["Omelette, avocat & pain complet","4 œufs · 100 g pain complet · 1/2 avocat · salade","2 œufs · 70 g pain complet · 1/2 avocat · salade"],dinner:["Poulet curry doux, riz & brocoli","180 g poulet · 90 g riz sec · 250 g brocoli","120 g poulet · 60 g riz sec · 250 g brocoli"],snack:["Pomme, noix & yaourt","1 pomme · 20 g noix · 1 skyr","1 pomme · 15 g noix · 1 yaourt"],shop:["6 œufs","300 g poulet","170 g pain complet","1 avocat","1 salade","4 tomates","150 g riz sec","500 g brocoli","140 ml lait de coco léger","2 pommes","35 g noix","2 yaourts"]},
    {name:"Jeudi",lunch:["Bowl lentilles, poulet, feta & crudités","160 g poulet · 180 g lentilles · 50 g feta · crudités","100 g poulet · 140 g lentilles · 40 g feta · crudités"],dinner:["Cabillaud, quinoa & courgettes","200 g cabillaud · 90 g quinoa sec · 300 g courgettes","140 g cabillaud · 60 g quinoa sec · 250 g courgettes"],snack:["Poire & skyr","1 poire · 250 g skyr","1 poire · 150 g skyr"],shop:["260 g poulet","340 g cabillaud","320 g lentilles cuites","90 g feta pasteurisée","150 g quinoa sec","550 g courgettes","1 concombre","3 tomates","2 carottes","2 poires","400 g skyr"]},
    {name:"Vendredi",lunch:["Bœuf sauté, nouilles & légumes","170 g bœuf · 90 g nouilles sèches · 300 g légumes","100 g bœuf · 60 g nouilles sèches · 250 g légumes"],dinner:["Burger poulet maison & patate douce","180 g poulet · 1 pain complet · 300 g patate douce","120 g poulet · 1 petit pain complet · 200 g patate douce"],snack:["Fromage blanc, kiwi & amandes","250 g fromage blanc · 1 kiwi · 20 g amandes","150 g fromage blanc · 1 kiwi · 15 g amandes"],shop:["270 g bœuf","300 g poulet","150 g nouilles sèches","2 pains complets","500 g patate douce","550 g légumes à sauter","1 salade","2 tomates","400 g fromage blanc","2 kiwis","35 g amandes"]},
    {name:"Samedi",lunch:["Couscous de dinde & légumes","180 g dinde · 90 g semoule sèche · légumes · pois chiches","120 g dinde · 60 g semoule sèche · légumes · pois chiches"],dinner:["Pizza maison poulet, mozzarella & légumes","1/2 grande pizza maison","1/3 à 1/2 grande pizza selon faim"],snack:["Fruit & skyr","1 fruit · 250 g skyr","1 fruit · 150 g skyr"],shop:["450 g dinde/poulet au total","150 g semoule sèche","200 g pois chiches cuits","550 g légumes couscous","1 pâte à pizza","1 bocal sauce tomate","150 g mozzarella pasteurisée","200 g champignons","1 poivron","400 g skyr","2 fruits"]},
    {name:"Dimanche",lunch:["Poulet rôti, pommes de terre & légumes","200 g poulet · 320 g pommes de terre · 300 g légumes","130 g poulet · 220 g pommes de terre · 250 g légumes"],dinner:["Soupe de lentilles, œufs & pain complet","300 g soupe · 3 œufs · 80 g pain complet","250 g soupe · 2 œufs · 60 g pain complet"],snack:["Yaourt & fruit","200 g yaourt · 1 fruit","150 g yaourt · 1 fruit"],shop:["330 g poulet","540 g pommes de terre","5 œufs","300 g lentilles cuites","140 g pain complet","1 poireau","5 carottes","2 courgettes","3 tomates","350 g yaourt","2 fruits"]}
  ];

  const style=document.createElement("style");
  style.textContent=`.tabbar{grid-template-columns:repeat(5,1fr)}.ff-switch{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;background:#111113;border:1px solid var(--line);padding:5px;border-radius:15px;margin:12px 0}.ff-switch button{border:0;background:transparent;color:var(--muted);padding:10px 5px;border-radius:11px;font-size:12px}.ff-switch button.active{background:#28282c;color:var(--text)}.ff-days{display:flex;gap:7px;overflow:auto;padding:2px 0 12px}.ff-days button{white-space:nowrap;border:1px solid var(--line);background:#111113;color:var(--muted);padding:9px 12px;border-radius:999px}.ff-days button.active{background:var(--accent);color:#15110b}.ff-meal{padding:14px 0;border-bottom:1px solid var(--line)}.ff-meal:last-child{border-bottom:0}.ff-portions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.ff-portion{padding:11px;border:1px solid var(--line);border-radius:14px;background:#101012;font-size:12px;line-height:1.45}.ff-portion b{display:block;color:var(--accent2);margin-bottom:4px}.ff-shop{display:flex;align-items:center;gap:11px;padding:12px 0;border-bottom:1px solid var(--line)}.ff-shop input{width:23px;height:23px;accent-color:var(--accent)}.ff-shop.done span{text-decoration:line-through;color:var(--muted)}.ff-week{padding:12px 0;border-bottom:1px solid var(--line)}@media(max-width:420px){.ff-portions{grid-template-columns:1fr}.tab small{font-size:9px}}`;
  document.head.appendChild(style);

  let day=(new Date().getDay()+6)%7;
  const getPerson=()=>localStorage.getItem(PERSON_KEY)||"both";
  const getView=()=>localStorage.getItem(VIEW_KEY)||"today";
  function dateKey(i){const n=new Date(),cur=(n.getDay()+6)%7,m=new Date(n.getFullYear(),n.getMonth(),n.getDate()-cur+i);return `${m.getFullYear()}-${m.getMonth()+1}-${m.getDate()}`;}
  const shopKey=i=>`forgefit_shop_${dateKey(i)}`;
  function readShop(i){try{return JSON.parse(localStorage.getItem(shopKey(i))||"[]");}catch(e){return[];}}
  function portion(x){const p=getPerson();if(p==="p1")return `<div class="ff-portion"><b>Jocelyn</b>${x[1]}</div>`;if(p==="p2")return `<div class="ff-portion"><b>Anaïs</b>${x[2]}</div>`;return `<div class="ff-portions"><div class="ff-portion"><b>Jocelyn</b>${x[1]}</div><div class="ff-portion"><b>Anaïs</b>${x[2]}</div></div>`;}
  function meal(label,x){return `<div class="ff-meal"><div class="eyebrow">${label}</div><h3 style="margin-top:6px">${x[0]}</h3>${portion(x)}</div>`;}
  function selectors(){const p=getPerson(),v=getView();return `<div class="ff-switch"><button data-p="both" class="${p==="both"?"active":""}">Nous deux</button><button data-p="p1" class="${p==="p1"?"active":""}">Jocelyn</button><button data-p="p2" class="${p==="p2"?"active":""}">Anaïs</button></div><div class="ff-switch"><button data-v="today" class="${v==="today"?"active":""}">Aujourd’hui</button><button data-v="week" class="${v==="week"?"active":""}">Semaine</button><button data-v="shop" class="${v==="shop"?"active":""}">Courses</button></div>`;}
  function days(){return `<div class="ff-days">${DAYS.map((d,i)=>`<button data-day="${i}" class="${i===day?"active":""}">${d.name}</button>`).join("")}</div>`;}
  function dayView(){const d=DAYS[day];return `<section class="card"><div class="row"><div><div class="eyebrow">MENU DU JOUR</div><h2 style="margin-top:5px">${d.name}</h2></div><span class="pill">Dîner ≈ 21 h</span></div>${meal("DÉJEUNER",d.lunch)}${meal("COLLATION OPTIONNELLE",d.snack)}${meal("DÎNER",d.dinner)}<div class="notice" style="margin-top:14px"><b>Jour muscu :</b> si besoin, ajoute une banane + 150 à 200 g de skyr autour de la séance plutôt que de réduire les repas.</div></section>`;}
  function weekView(){return `<section class="card"><div class="eyebrow">MENU 7 JOURS</div><h2 style="margin:6px 0">La semaine</h2>${DAYS.map((d,i)=>`<div class="ff-week"><div class="row"><b>${d.name}</b><button class="ghost" data-open="${i}">Voir</button></div><div class="small muted" style="margin-top:5px">Midi : ${d.lunch[0]}<br>Soir : ${d.dinner[0]}</div></div>`).join("")}</section>`;}
  function shopView(){const d=DAYS[day],done=readShop(day);return `<section class="card"><div class="row"><div><div class="eyebrow">COURSES DU JOUR</div><h2 style="margin-top:5px">${d.name}</h2></div><span class="pill">${done.length}/${d.shop.length}</span></div><p class="muted small">Quantités pour vous deux. La liste change chaque jour.</p>${d.shop.map((x,i)=>`<label class="ff-shop ${done.includes(i)?"done":""}"><input type="checkbox" data-shop="${i}" ${done.includes(i)?"checked":""}><span>${x}</span></label>`).join("")}<button class="ghost full" id="reset-shop" style="margin-top:12px">Réinitialiser</button></section>`;}
  function renderMeals(){const v=getView();view.innerHTML=`<section class="card hero"><div class="eyebrow">FORGEFIT DUO</div><div class="hero-title">Repas & courses</div><p class="muted">Même menu, portions adaptées, courses possibles tous les jours.</p>${selectors()}</section>${days()}${v==="today"?dayView():v==="week"?weekView():shopView()}<section class="card"><div class="eyebrow">ACCÈS DUO</div><h3 style="margin-top:6px">Partager les repas à Anaïs</h3><p class="muted small">Elle peut ouvrir ce lien sur son iPhone et ajouter ForgeFit à son écran d’accueil. Les coches de courses restent locales à son téléphone.</p><button class="primary full" id="share-duo">Partager le lien</button></section>`;
    view.querySelectorAll("[data-p]").forEach(b=>b.onclick=()=>{localStorage.setItem(PERSON_KEY,b.dataset.p);renderMeals();});
    view.querySelectorAll("[data-v]").forEach(b=>b.onclick=()=>{localStorage.setItem(VIEW_KEY,b.dataset.v);renderMeals();});
    view.querySelectorAll("[data-day]").forEach(b=>b.onclick=()=>{day=+b.dataset.day;renderMeals();});
    view.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>{day=+b.dataset.open;localStorage.setItem(VIEW_KEY,"today");renderMeals();});
    view.querySelectorAll("[data-shop]").forEach(c=>c.onchange=()=>{let a=readShop(day),i=+c.dataset.shop;a=c.checked?[...new Set([...a,i])]:a.filter(x=>x!==i);localStorage.setItem(shopKey(day),JSON.stringify(a));renderMeals();});
    view.querySelector("#reset-shop")?.addEventListener("click",()=>{localStorage.removeItem(shopKey(day));renderMeals();});
    view.querySelector("#share-duo")?.addEventListener("click",async()=>{const url=`${location.origin}${location.pathname}?view=meals&duo=1`;if(navigator.share){try{await navigator.share({title:"ForgeFit — Repas & courses",text:"Nos repas et courses du jour",url});return;}catch(e){}}try{await navigator.clipboard.writeText(url);alert("Lien copié.");}catch(e){prompt("Copie ce lien",url);}});
  }
  const baseRender=render;
  render=function(){if(route==="meals"){title.textContent="Repas & courses";renderMeals();return;}baseRender();};
  const q=new URLSearchParams(location.search);if(q.get("duo")==="1")localStorage.setItem(PERSON_KEY,"p2");if(q.get("view")==="meals")setRoute("meals");
})();