// Denat Life V27 — UX séance concentrée sur une série à la fois.
(function(){
 const fmt=n=>{n=+n||0;return Number.isInteger(n)?String(n):n.toFixed(1).replace(".",",")},done=e=>(e?.sets||[]).filter(x=>x.done),all=e=>e.sets?.length&&e.sets.every(x=>x.done);
 let undo=null,wake=null;
 const idx=()=>{const s=state.activeSession;if(!s)return 0;const x=+s.uiExerciseIndex;if(Number.isInteger(x)&&x>=0&&x<s.exercises.length&&!all(s.exercises[x]))return x;const i=s.exercises.findIndex(e=>!all(e));return i<0?s.exercises.length-1:i};
 const setIdx=e=>{const i=e.sets.findIndex(x=>!x.done);return i<0?e.sets.length-1:i};
 const step=e=>e.category==="lower"?(+state.settings.lowerIncrement||5):(+state.settings.upperIncrement||2.5);
 const coach=e=>window.DenatSportCoach?.livePlan?.(e)||{weight:e.suggestedWeight||0,reps:e.targetReps||10,rpe:"7–8",reason:"Exécution propre."};
 const previous=name=>{const e=window.DenatSportCoach?.history?.(name,1)?.[0]?.ex,a=done(e);return a.length?a.slice(0,4).map(x=>`${fmt(x.weight)}×${x.reps}${x.rpe?` @${x.rpe}`:""}`).join(" · "):"Aucune référence"};
 function progress(s){const total=s.exercises.reduce((a,e)=>a+e.sets.length,0),ok=s.exercises.reduce((a,e)=>a+done(e).length,0);return{total,ok,pct:total?Math.round(ok/total*100):0}}
 function jump(i){const s=state.activeSession;if(!s)return;s.uiExerciseIndex=Math.max(0,Math.min(s.exercises.length-1,i));saveState();renderActiveSession()}
 function sync(set){const w=document.querySelector("#ux-w"),r=document.querySelector("#ux-r");if(w)set.weight=w.value.replace(",",".");if(r)set.reps=r.value;saveState()}
 function change(ex,set,k,d){sync(set);let v=+set[k]||0;set[k]=k==="weight"?Math.max(0,Math.round((v+d)*100)/100):Math.max(0,Math.round(v+d));saveState();renderActiveSession()}
 function validate(ei,si){const s=state.activeSession,ex=s.exercises[ei],set=ex.sets[si];if(set.done)return;sync(set);const p=coach(ex);if(set.weight===""&&p.weight)set.weight=p.weight;if(set.reps===""&&p.reps)set.reps=p.reps;undo={ei,si,set:{...set}};set.done=true;ex._firstSetAt=ex._firstSetAt||new Date().toISOString();ex._lastSetAt=new Date().toISOString();if(all(ex)){const n=s.exercises.findIndex((x,i)=>i>ei&&!all(x));if(n>=0)s.uiExerciseIndex=n}saveState();startRestTimer(+ex.rest||+state.settings.defaultRest||90);renderActiveSession()}
 function undoLast(){if(!undo)return;const s=state.activeSession,set=s?.exercises?.[undo.ei]?.sets?.[undo.si];if(!set)return;Object.assign(set,undo.set);s.uiExerciseIndex=undo.ei;undo=null;stopTimer();saveState();renderActiveSession()}
 async function awake(){if(!navigator.wakeLock||wake)return;try{wake=await navigator.wakeLock.request("screen");wake.addEventListener?.("release",()=>wake=null)}catch(e){}}
 function release(){try{wake?.release?.()}catch(e){}wake=null}
 function strip(s,ei){return `<div class="ux-strip">${s.exercises.map((e,i)=>`<button data-jump="${i}" class="${i===ei?"active":""} ${all(e)?"done":""}"><span>${all(e)?"✓":i===ei?"●":"○"}</span><b>${esc(e.name)}</b><small>${done(e).length}/${e.sets.length}</small></button>`).join("")}</div>`}
 function renderUX(){
  const s=state.activeSession;if(!s)return;awake();const ei=idx(),ex=s.exercises[ei],si=setIdx(ex),set=ex.sets[si],p=coach(ex),pr=progress(s),st=step(ex),last=done(ex).at(-1);title.textContent=s.workoutName;
  if(!set.done){if((set.weight===""||set.weight==null)&&p.weight)set.weight=p.weight;if((set.reps===""||set.reps==null)&&p.reps)set.reps=p.reps}
  view.innerHTML=`<section class="ux-head"><div><div class="eyebrow">SÉANCE EN COURS</div><b>${esc(s.workoutName)}</b></div><div><span>${pr.ok}/${pr.total}</span><button class="ghost" id="ux-menu">•••</button></div><i><span style="width:${pr.pct}%"></span></i></section>
  ${strip(s,ei)}
  <section class="card ux-focus"><div class="row"><div><div class="eyebrow">EXERCICE ${ei+1}/${s.exercises.length} · SÉRIE ${si+1}/${ex.sets.length}</div><h2>${esc(ex.name)}</h2></div><button class="ff-thumb" data-tech><span>TECHNIQUE</span></button></div>
  <div class="ux-tech-inline">${window.FFGuide?.motion?.(ex.name,true)||window.FFGuide?.svg?.(window.FFGuide?.info?.(ex.name)?.type||"generic")||""}</div><div class="ux-last"><span>Dernière fois</span><b>${esc(previous(ex.name))}</b></div><div class="ux-target"><span>Cible</span><b>${p.finished?"Terminé":esc(p.text||"")}</b><small>RPE ${esc(p.rpe||"7–8")}</small></div>
  ${!p.finished?`<div class="ux-control"><label>CHARGE</label><div><button data-k="weight" data-d="-${st}">−</button><input id="ux-w" inputmode="decimal" value="${esc(set.weight)}"><button data-k="weight" data-d="${st}">+</button></div><small>± ${fmt(st)} kg</small></div>
  <div class="ux-control"><label>RÉPÉTITIONS</label><div><button data-k="reps" data-d="-1">−</button><input id="ux-r" inputmode="numeric" value="${esc(set.reps)}"><button data-k="reps" data-d="1">+</button></div></div>
  <div class="ux-rpe"><label>RPE</label><div>${[6,7,8,9,10].map(x=>`<button data-rpe="${x}" class="${+set.rpe===x?"active":""}">${x}</button>`).join("")}</div><small>6 facile · 8 ≈ 2 reps en réserve · 10 max</small></div><button class="primary full ux-ok" id="ux-ok">✓ Valider la série ${si+1}</button>`:`<div class="notice">✓ Exercice terminé</div>`}
  ${undo?`<button class="ghost full" id="ux-undo">Annuler la dernière validation</button>`:""}${last?`<p class="small muted">Dernière série : ${fmt(last.weight)} kg × ${last.reps}${last.rpe?` · RPE ${last.rpe}`:""}</p>`:""}
  <div class="ux-session-shortcuts"><button class="ghost" data-replace-exercise>Machine occupée ?</button><button class="ghost" data-hotel-exercise>🏨 Sans machine</button><button class="ghost" data-tech>Voir le bonhomme</button></div><details class="ux-details"><summary>Technique & détails</summary><div class="stack"><button class="ghost full" data-tech>Voir le mouvement</button><div class="notice small"><b>Coach</b><br>${esc(p.reason||"")}</div></div></details></section>
  <section class="ux-bottom"><button class="ghost" id="ux-prev" ${ei===0?"disabled":""}>←</button><button class="primary" id="ux-finish">Terminer</button><button class="ghost" id="ux-next" ${ei===s.exercises.length-1?"disabled":""}>→</button></section>`;
  bind(s,ei,ex,set,si)
 }
 function bind(s,ei,ex,set,si){
  view.querySelectorAll("[data-jump]").forEach(b=>b.onclick=()=>jump(+b.dataset.jump));view.querySelectorAll("[data-k]").forEach(b=>b.onclick=()=>change(ex,set,b.dataset.k,+b.dataset.d));view.querySelectorAll("[data-rpe]").forEach(b=>b.onclick=()=>{sync(set);set.rpe=+b.dataset.rpe;saveState();renderActiveSession()});view.querySelectorAll("[data-tech]").forEach(b=>b.onclick=()=>window.FFGuide?.open?.(ex.name));view.querySelector("[data-replace-exercise]")?.addEventListener("click",replaceExercise);view.querySelector("[data-hotel-exercise]")?.addEventListener("click",()=>smartReplace("hotel"));view.querySelector("#ux-ok")?.addEventListener("click",()=>validate(ei,si));view.querySelector("#ux-undo")?.addEventListener("click",undoLast);view.querySelector("#ux-prev")?.addEventListener("click",()=>jump(ei-1));view.querySelector("#ux-next")?.addEventListener("click",()=>jump(ei+1));view.querySelector("#ux-menu")?.addEventListener("click",menu);view.querySelector("#ux-finish")?.addEventListener("click",finishPreview)
 }
 function applyReplacement(newDef){
   const s=state.activeSession,ei=idx(),old=s.exercises[ei],sets=old.sets||[],completed=sets.filter(x=>x.done);
   s.exercises[ei]={...old,name:newDef.name,category:newDef.category,libraryId:newDef.id,muscles:[...newDef.muscles],equipment:[...newDef.equipment],rest:newDef.rest,targetReps:newDef.reps,sets:sets.map((x,i)=>x.done?x:{...x,weight:"",reps:newDef.reps,rpe:"",done:false,index:i+1}),replacedFrom:old.name};
   saveState();renderActiveSession();
 }
 function smartReplace(mode="similar"){
   const s=state.activeSession,ei=idx(),current=s.exercises[ei],lib=window.DenatExerciseLibrary;if(!lib)return;
   const choices=lib.alternatives?.(current.name,mode)||[];
   const modal=document.createElement("div");modal.className="ff-modal ux-alt";modal.innerHTML=`<div class="ff-modal-card"><div class="row"><div><div class="eyebrow">${mode==="hotel"?"SANS MACHINE / HÔTEL":"MACHINE OCCUPÉE"}</div><h3 style="margin:5px 0">Remplacer ${esc(current.name)}</h3></div><button class="ghost" data-close>Fermer</button></div><p class="muted small">Alternatives classées selon les muscles travaillés.</p><div class="stack">${choices.map((x,i)=>`<button class="secondary full ux-alt-item" data-alt="${x.id}"><b>${i+1}. ${esc(x.name)}</b><small>${esc(x.group)} · ${esc(x.equipment.join(" + "))}</small></button>`).join("")||'<div class="empty">Aucune alternative adaptée trouvée.</div>'}</div><button class="ghost full" data-library style="margin-top:10px">Voir toute la bibliothèque</button></div>`;document.body.appendChild(modal);
   modal.querySelector("[data-close]").onclick=()=>modal.remove();modal.querySelectorAll("[data-alt]").forEach(b=>b.onclick=()=>{const def=lib.exercises.find(x=>x.id===b.dataset.alt);modal.remove();if(def)applyReplacement(def)});modal.querySelector("[data-library]").onclick=()=>{modal.remove();lib.open({onChoose:applyReplacement})};
 }
 function replaceExercise(){smartReplace("similar")}

 function menu(){const m=document.createElement("div");m.className="ff-modal ux-menu";m.innerHTML=`<div class="ff-modal-card"><div class="row"><h3>Options</h3><button class="ghost" data-x>Fermer</button></div><div class="stack" style="margin-top:14px"><button class="secondary full" data-hotel-session>🏨 Adapter toute la séance sans machine</button><button class="secondary full" data-replace-ex>Machine occupée · remplacer l’exercice</button><button class="secondary full" data-tech-menu>Technique du mouvement</button><button class="secondary full" data-add>+ Ajouter une série</button><button class="danger full" data-cancel>Annuler la séance</button></div></div>`;document.body.appendChild(m);m.querySelector("[data-x]").onclick=()=>m.remove();m.querySelector("[data-hotel-session]")?.addEventListener("click",()=>{m.remove();window.DenatNomad?.adaptActiveSession?.()});m.querySelector("[data-replace-ex]").onclick=()=>{m.remove();replaceExercise()};m.querySelector("[data-tech-menu]").onclick=()=>{const ex=state.activeSession.exercises[idx()];m.remove();window.FFGuide?.open?.(ex.name)};m.querySelector("[data-add]").onclick=()=>{const ex=state.activeSession.exercises[idx()],l=ex.sets.at(-1);ex.sets.push({id:crypto.randomUUID(),index:ex.sets.length+1,weight:l?.weight||ex.suggestedWeight||"",reps:ex.targetReps,rpe:"",done:false});ex.targetSets=ex.sets.length;saveState();m.remove();renderActiveSession()};m.querySelector("[data-cancel]").onclick=()=>{if(confirm("Annuler cette séance ?")){release();state.activeSession=null;saveState();m.remove();render()}}}
 function finishPreview(){const s=state.activeSession,pr=progress(s),mins=Math.max(1,Math.round((Date.now()-new Date(s.startedAt))/60000)),vol=Math.round(sessionVolume(s)),m=document.createElement("div");m.className="ff-modal ux-finish";m.innerHTML=`<div class="ff-modal-card"><div class="eyebrow">FIN DE SÉANCE</div><h2>${esc(s.workoutName)}</h2><div class="ux-summary"><div><b>${mins}</b><span>minutes</span></div><div><b>${pr.ok}</b><span>séries</span></div><div><b>${vol.toLocaleString("fr-FR")}</b><span>kg volume</span></div></div>${pr.ok<pr.total?`<div class="notice small">${pr.total-pr.ok} série(s) non validée(s).</div>`:""}<div class="stack"><button class="primary full" data-save>Enregistrer et terminer</button><button class="ghost full" data-back>Retour</button></div></div>`;document.body.appendChild(m);m.querySelector("[data-back]").onclick=()=>m.remove();m.querySelector("[data-save]").onclick=()=>{m.remove();release();finishSession()}}
 function timer30(){const a=document.querySelector("#timer-sheet .timer-actions");if(!a||a.querySelector("#ux-plus30"))return;const b=document.createElement("button");b.id="ux-plus30";b.className="secondary";b.textContent="+30 s";b.onclick=()=>{timerEnd+=30000;updateTimer()};a.appendChild(b)}
 const base=renderActiveSession;renderActiveSession=function(){if(!state.activeSession)return base();renderUX();timer30()};
 document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible"&&state.activeSession)awake()});
 const style=document.createElement("style");style.textContent=`.ux-head{padding:10px 4px 12px;display:grid;grid-template-columns:1fr auto;gap:8px}.ux-head>div{display:flex;align-items:center;gap:8px}.ux-head>div:first-child{display:block}.ux-head i{grid-column:1/-1;height:5px;background:#171719;border-radius:9px;overflow:hidden}.ux-head i span{display:block;height:100%;background:var(--accent2)}.ux-strip{display:flex;gap:7px;overflow:auto;padding:0 0 12px;scrollbar-width:none}.ux-strip button{min-width:132px;text-align:left;border:1px solid var(--line);background:#101012;color:var(--muted);border-radius:14px;padding:9px;display:grid;grid-template-columns:auto 1fr auto;gap:5px}.ux-strip button.active{border-color:var(--accent2);color:var(--text)}.ux-strip button.done{opacity:.6}.ux-strip b{font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ux-strip small{font-size:9px}.ux-focus{padding:16px}.ux-tech-inline{height:110px;display:grid;place-items:center;color:var(--accent2);margin:6px 0}.ux-tech-inline svg{height:105px;max-width:180px}.ux-last,.ux-target{display:flex;flex-direction:column;gap:3px;padding:10px 0;border-bottom:1px solid var(--line)}.ux-last span,.ux-target span,.ux-control label,.ux-rpe label{font-size:10px;color:var(--muted);letter-spacing:.12em}.ux-target b{font-size:20px;color:var(--accent2)}.ux-control{margin:18px 0}.ux-control>div{display:grid;grid-template-columns:64px 1fr 64px;gap:8px;margin-top:6px}.ux-control button{border:1px solid var(--line);background:#1b2a40;color:white;border-radius:16px;font-size:28px;font-weight:800}.ux-control input{font-size:30px;font-weight:850;text-align:center;padding:13px 6px}.ux-control small,.ux-rpe small{display:block;text-align:center;color:var(--muted);font-size:10px;margin-top:5px}.ux-rpes,.ux-rpe>div{display:grid;grid-template-columns:repeat(5,1fr);gap:6px;margin-top:7px}.ux-rpe button{padding:12px 4px;border-radius:13px;border:1px solid var(--line);background:#101012;color:var(--muted);font-weight:800}.ux-rpe button.active{background:var(--accent);color:white}.ux-ok{margin-top:18px;padding:17px;font-size:16px}.ux-session-shortcuts{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:12px}.ux-details{margin-top:15px}.ux-details summary{color:var(--muted);font-size:12px;padding:8px 0}.ux-bottom{position:sticky;bottom:78px;display:grid;grid-template-columns:64px 1fr 64px;gap:8px;padding:10px;background:rgba(8,17,31,.94);backdrop-filter:blur(12px);border:1px solid var(--line);border-radius:18px;z-index:7}.ux-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:16px 0}.ux-summary div{padding:12px;border:1px solid var(--line);border-radius:14px}.ux-summary b{display:block;font-size:22px}.ux-summary span{font-size:10px;color:var(--muted)}#timer-sheet .timer-actions{grid-template-columns:repeat(4,1fr)}@media(max-width:420px){.ux-control>div{grid-template-columns:58px 1fr 58px}.ux-target b{font-size:18px}}`;document.head.appendChild(style);
 window.DenatSessionUX={render:renderUX,activeIndex:idx,progress,undoLast};if(state.activeSession)renderActiveSession()
})();